### ISSUE TITLE
About the all landmarks of SynthFace

### ISSUE THREAD

**Issue by fdyuandong** [microsoft/SynthMoCap#5]
Very good work and data—truly insightful! I have a question regarding the SynthFace dataset. The paper states that 744 keypoints were directly regressed, but the open-source data only contains annotations for 70 keypoints. Could you please provide the complete annotation information for all 744 keypoints?

**Comment by friggog** [comment]
Hi - unfortunately we don't have permission to redistribute the high-fidelity face data, so can only release the sparse facial landmarks and head/eye pose information as currently included in the dataset
