### ISSUE TITLE
About human model creation

### ISSUE THREAD

**Issue by chuanfushen** [microsoft/SynthMoCap#6]
Awesome work, I would like to know any plan to release the pipeline of human model generation.

Besides, how clothing and hair added into SMPLH model.

Appreciate the awesome work again!

**Comment by friggog** [comment]
Hey - for the body and hand data clothing is added using displacement maps so adapts automatically to the body shape/pose, for the face data we have 3D mesh clothing which is warped to fit around the neck. The hair is represented as individual strands using blender particle systems. The hair assets are authored on a template mesh and warped based on the difference of the current head shape to the template. There are some details provided in the paper/supplementary material available here: https://arxiv.org/abs/2410.11520
