### ISSUE TITLE
face mesh using visualize_data.py

### ISSUE THREAD

**Issue by minjung98** [microsoft/SynthMoCap#7]
This seems like a really interesting project. Is it possible to visualize only the facial mesh like in the image below using visualize_data.py? Would it be possible to extract just the facial pose information?

![Image](https://github.com/user-attachments/assets/9351a145-1f04-4c8d-8026-9a0835b86d89)

**Comment by friggog** [comment]
Hi - unfortunately we don't have permission to redistribute the high-fidelity face data, so can only release the sparse facial landmarks and head/eye pose information as currently included in the dataset
